title: abapOpenChecks
highlighter: rouge
permalink: pretty
collections:
  checks:
    output: true
plugins:
  - jekyll-octicons    
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"